import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`flex flex-col min-h-screen ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* ------- Header ----- */}
        <Navbar />
        <hr />

        {/* ------- Main Part ----- */}
        <main className="flex-grow">{children}</main>

        {/* ------- Footer ----- */}
        <footer className="text-center">
          <h2>This is footer part</h2>
        </footer>
      </body>
    </html>
  );
}
